name: Task Creation
description: Structured template for new tasks
title: "[TASK] - <short description>"
labels: ["task"]
body:
  - type: input
    id: task-id
    attributes:
      label: "Task ID"
      placeholder: "T-000X"
    validations:
      required: true
  - type: textarea
    id: task-desc
    attributes:
      label: "Description"
      placeholder: "Provide a detailed description."
    validations:
      required: true
  - type: dropdown
    id: task-size
    attributes:
      label: "Estimated Effort"
      options:
        - "≤6h"
        - ">6h"
    validations:
      required: true
  - type: input
    id: parent-task
    attributes:
      label: "Parent Task"
      placeholder: "T-XXXX (optional)"
    validations:
      required: false
