name: Daily Blocker Scan

on:
  schedule:
    - cron: '0 6 * * *'  # 09:00 Europe/Istanbul

jobs:
  blocker-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan blockers
        run: |
          # runs daily and targets issues labelled risk:blocker
          gh issue list --label risk:blocker --state open --json title,number,html_url \
            | jq -r '.[] | "- [#\(.number)](\(.html_url)) \(.title)"' > blockers.tmp
          [ -s blockers.tmp ] || exit 0
          gh issue create --title "🚨 Blockers Detected $(date '+%Y-%m-%d')" \
                          --body "$(cat blockers.tmp)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
