# File: .github/workflows/gpt-cmd.yml
name: ChatGPT Command Parser

on:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  parse-and-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Parse and apply GPT-CMD directives
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "⏳ Extracting GPT-CMD lines from issue body…"
          DIRECTIVES=$(printf "%s\n" "${{ github.event.issue.body }}" | grep -E '^(UPDATE|CREATE|CLOSE)')
          if [ -z "$DIRECTIVES" ]; then
            echo "✅ No GPT-CMD directives found → skipping."
            exit 0
          fi

          echo "➡️  Applying the following directives:"
          printf "%s\n\n" "$DIRECTIVES"

          # Apply UPDATE directives to Tasks.md
          printf "%s\n" "$DIRECTIVES" | while read -r line; do
            case "$line" in
              UPDATE*)
                # Extract the pattern & replacement parts
                # Format: UPDATE Tasks.md<newline>pattern: "...“<newline>replacement: "..."
                # Use a simple awk/sed pipeline or call a helper script here.
                # For now, just append the UPDATE block for manual review:
                echo "$line" >> Tasks.md
                ;;
              CREATE*)
                # You could invoke gh CLI here:
                # echo "$line" | gh issue create --title "$(…)" --body "$(…)"
                echo "$line" # stub
                ;;
              CLOSE*)
                # echo "$line" | gh issue close $(…)
                echo "$line" # stub
                ;;
            esac
          done

          # Commit & push only if Tasks.md changed
          git config user.name "gpt-automation"
          git config user.email "gpt-automation@github.com"
          git add Tasks.md
          if git diff --cached --quiet; then
            echo "✅ No changes to Tasks.md → skipping commit."
          else
            git commit -m "GPT Command executed from issue #${{ github.event.issue.number }}"
            git push
          fi
