# File: .github/workflows/gpt-cmd.yml
name: ChatGPT Command Parser

on:
  issues:
    types: [opened]

jobs:
  parse-and-apply:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # grant push permissions
    if: contains(github.event.issue.title, '[GPT-CMD]')
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true     
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ github.event.issue.body }}" >> Tasks.md
          git config user.name "gpt-automation"
          git config user.email "gpt-automation@github.com"
          git add Tasks.md
          if git diff --cached --quiet; then
            echo "No changes to commit → skipping."
          else
            git commit -m "GPT Command executed from issue #${{ github.event.issue.number }}"
            git push
          fi
