name: ChatGPT Command Parser

on:
  issues:
    types: [opened, edited, reopened]

permissions:
  contents: write   # allows git push from workflow
  issues: write     # allows issue updates/comments if needed

jobs:
  parse-and-apply:
    if: contains(github.event.issue.title, '[GPT-CMD]')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Apply GPT Command
        env:
          CMD_BODY: ${{ github.event.issue.body }}
        run: |
          # Safely append body to Tasks.md
          printf '%s\n' "$CMD_BODY" >> Tasks.md

          git config user.name "gpt-automation"
          git config user.email "gpt-automation@github.com"
          git commit -am "GPT Command executed from issue #${{ github.event.issue.number }}" || true
          git push
