name: ChatGPT Command Parser

on:
  issues:
    types: [opened, edited, reopened]

permissions:
  contents: write
  issues:   write

jobs:
  parse-and-apply:
    if: contains(github.event.issue.title, '[GPT-CMD]')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Apply GPT Command
        env:
          CMD_BODY: ${{ github.event.issue.body }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/parse_gpt_cmd.py

      - name: Commit & Push
        run: |
          git config user.name "gpt-automation"
          git config user.email "gpt-automation@github.com"
          git commit -am "GPT Command executed from issue #${{ github.event.issue.number }}" || true
          git push
