# --- Create live PH-00 task issues ---
CREATE issue
title: "[TASK] T-0005 Create first snapshot generator"
labels: ["task", "task:open"]
body: |
  **Task-ID:** T-0005  
  **Description:** Create and validate the snapshot generator (`summary.yml`) so that `Snapshots/YYYY-MM-DD.md` is produced and committed.  
  **Effort:** ≤ 6 h  
  **Exit-Criteria:** Workflow run green; snapshot file present in `main`.

CREATE issue
title: "[TASK] T-0006 Clarify templates & add example"
labels: ["task", "task:open"]
body: |
  **Task-ID:** T-0006  
  **Description:** Add a fully filled example of `ISSUE_TEMPLATE/task.yml` under `docs/examples/` and link it from `Governance.md`.  
  **Effort:** ≤ 6 h  
  **Exit-Criteria:** Example committed; docs updated.

CREATE issue
title: "[TASK] T-0007 Insert Phase-Gate checklist & labels"
labels: ["task", "task:open"]
body: |
  **Task-ID:** T-0007  
  **Description:** Define labels `phase:pending-review` and `phase:approved`; embed a Phase-Gate checklist in `Governance.md`.  
  **Effort:** ≤ 6 h  
  **Exit-Criteria:** Labels exist; checklist merged.

CREATE issue
title: "[TASK] T-0008 Add Disaster-Recovery note & script"
labels: ["task", "task:open"]
body: |
  **Task-ID:** T-0008  
  **Description:** Flesh out `scripts/restore_ctx.ps1` to restore the latest snapshot and reopen any `risk:blocker` tasks; document usage in `Governance.md`.  
  **Effort:** ≤ 6 h  
  **Exit-Criteria:** Script tested; documentation updated.

CREATE issue
title: "[TASK] T-0009 Create weekly cleanup Action"
labels: ["task", "task:open"]
body: |
  **Task-ID:** T-0009  
  **Description:** Ensure `cleanup.yml` archives stale Work-Stream Issues; verify via manual `workflow_dispatch`.  
  **Effort:** ≤ 6 h  
  **Exit-Criteria:** Dispatch passes; stale Issues labeled `archived`.

CREATE issue
title: "[TASK] T-0010 Implement GPT-CMD parser (auto-exec UPDATE/CREATE)"
labels: ["task", "task:open"]
body: |
  **Task-ID:** T-0010  
  **Description:** Finalize `scripts/parse_gpt_cmd.py` so patterns are auto-escaped (`re.escape`) unless prefixed with `r"…"`, and remove sandbox debug prints.  
  **Effort:** ≤ 6 h  
  **Exit-Criteria:** Unit test validates literal-pattern update; docs aligned; CI green.
